[workspace]
members = [
    "xtask",
]

[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.2.1", features = ["derive", "env"] }
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0"
sqlx  = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
thiserror = "1.0.40"
tokio = { version = "1.26", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
uuid  = { version = "1.3.0", features = [ "v4", "serde" ] }

[dev-dependencies]
hyper = { version = "0.14.25", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
