[workspace]
members = ["xtask"]

[package]
name = "api"
description = "A cleanly designed Rust REST Api"
version = "0.1.0"
edition = "2021"
authors = ["Tristan J. Schoenmakers <tristansjh@gmail.com>"]
repository = "https://github.com/TristanJSchoenmakers/clean-architecture"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.2.5", features = ["derive", "env"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0"
sqlx  = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
thiserror = "1.0.40"
tokio = { version = "1.28", features = ["full"] }
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
uuid  = { version = "1.3.1", features = [ "v4", "serde" ] }
validator = { version = "0.16.0", features = ["derive"] }

[dev-dependencies]
hyper = { version = "0.14.26", features = ["full"] }
pretty_assertions = "1.3.0"
tower = { version = "0.4.13", features = ["util"] }
