[workspace]
members = [
    "xtask",
]

[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum  = "0.6"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0"
sqlx  = { version = "0.6", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.26", features = ["full"] }
uuid = "1.3.0"
