version: '3.1'
services:
  api:
    image: tristanjschoenmakers/clean-axum-api
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD:-password}@db:5432/api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local