[env]
DATABASE_URL = "postgres://postgres:example@localhost/mytest"

# Flow: initialize

# Linux sudo issue: https://docs.docker.com/engine/install/linux-postinstall/
[tasks.docker]
command = "docker"
args = ["compose", "up", "--detach"]

[tasks.db-create]
install_crate = "sqlx-cli"
command = "sqlx"
args = ["database", "create"]

[tasks.db-migrate]
command = "sqlx"
args = ["migrate", "run"]
dependencies = ["db-create"]

[tasks.db-seed]
command = "sqlx"
args = ["migrate", "run", "--source", "migrations/seeds", "--ignore-missing"]
dependencies = ["db-create"]

[tasks.init]
dependencies = [
  "docker",
  "db-create",
  "db-migrate",
  "db-seed"
]

[tasks.run]
command = "cargo"
args = ["run"]
