# Cargo configuration keys and their definitions at https://doc.rust-lang.org/cargo/reference/config.html

[alias]
xtask = "run -q --package xtask --"

[env]
DATABASE_URL = "postgres://postgres:password@localhost/api"
RUST_LOG = "api=DEBUG,sqlx=DEBUG,tower_http=DEBUG,axum::rejection=trace"